#!/usr/bin/perl

use strict;
use warnings;
use File::Slurp qw(read_file);
use JavaScript::Beautifier qw(js_beautify);

@ARGV && -f $ARGV[0] or die "usage: $0 <js_file>\n";

print js_beautify(
                  scalar read_file(shift) => {
                                              indent_size      => 1,
                                              indent_character => "\t",
                                             }
                 );
