#!/usr/bin/perl

use 5.036;
use ntheory qw(:all);

# Pohlig-Hellman with Pollard's rho for each prime-power factor.

# Pollard's rho algorithm for logarithms
# https://en.wikipedia.org/wiki/Pollard%27s_rho_algorithm_for_logarithms

# Pollard's rho for groups of prime order p
sub __prime_order_log__($g, $h, $p, $n, $max_tries = 100) {

    # Trivial cases
    return 0 if ($h == 1);
    return 1 if ($g == $h);

    # For very small prime orders, brute force is simpler and reliable
    if ($p <= 1000) {
        my $t = 1;
        for my $i (0 .. $p - 1) {
            return $i if $t == $h;
            $t = mulmod($t, $g, $n);
        }
        return undef;
    }

    foreach my $attempt (1 .. $max_tries) {

        # Random starting point (a,b) with X = g^a * h^b
        my $a1 = urandomm($p);
        my $b1 = urandomm($p);
        my $x1 = mulmod(powmod($g, $a1, $n), powmod($h, $b1, $n), $n);

        my $a2 = $a1;
        my $b2 = $b1;
        my $x2 = $x1;

        # Floyd's cycle detection
        my $iter = sub($a, $b, $x) {
            my $r = ($x % 3);
            if ($r == 0) {
                $a = addmod($a, 1, $p);
                $x = mulmod($x, $g, $n);
            }
            elsif ($r == 1) {
                $b = addmod($b, 1, $p);
                $x = mulmod($x, $h, $n);
            }
            else {
                $a = mulmod(2,  $a, $p);
                $b = mulmod(2,  $b, $p);
                $x = mulmod($x, $x, $n);
            }
            return ($a, $b, $x);
        };

        while (1) {

            # Tortoise step
            ($a1, $b1, $x1) = $iter->($a1, $b1, $x1);

            # Hare step (two iterations)
            ($a2, $b2, $x2) = $iter->($a2, $b2, $x2);
            ($a2, $b2, $x2) = $iter->($a2, $b2, $x2);

            if ($x1 == $x2) {

                # Collision: g^{a1} h^{b1} = g^{a2} h^{b2}
                my $da = submod($a1, $a2, $p);
                my $db = submod($b2, $b1, $p);

                if ($db == 0) {
                    last;    # degenerate case, restart
                }

                my $x = mulmod($da, invmod($db, $p), $p);

                if (powmod($g, $x, $n) == $h) {
                    return $x;
                }
                last;    # verification failed, restart
            }
        }
    }

    return undef;    # failed after max_tries
}

# Solve g^x = a (mod n) where g has order exactly p^e * r,
# and we want x modulo p^e.
sub __prime_power_log__($a, $g, $n, $p, $e, $full_order) {

    my $L = $full_order;
    my $r = divint($L, powint($p, $e));    # co-factor

    # Move into the subgroup of order p^e
    my $g0 = powmod($g, $r, $n);
    my $a0 = powmod($a, $r, $n);

    my $x     = 0;
    my $cur_g = $g0;                       # current generator, order p^{e-i}
    my $cur_a = $a0;                       # current element
    my $f     = 1;                         # current digit multiplier

    foreach my $i (0 .. $e - 1) {

        # Create an element of order p by raising to p^{e-1-i}
        my $exp   = powint($p, $e - $i - 1);
        my $sub_g = powmod($cur_g, $exp, $n);    # generator of order p
        my $sub_a = powmod($cur_a, $exp, $n);    # corresponding element

        # Solve the discrete log in the prime-order subgroup
        my $d = __prime_order_log__($sub_g, $sub_a, $p, $n) // return (undef, 0);

        $x += ($d * $f);
        $f *= $p;

        # Remove the already found part
        $cur_a = mulmod($cur_a, powmod($cur_g, -$d, $n), $n);
        $cur_g = powmod($cur_g, $p, $n);    # next generator, order p^{e-1-i}
    }

    return ($x, 1);
}

# Solve g^x = a (mod n) where gcd(g, n) = 1, using Pohlig-Hellman over order of g.
# Suitable when n is a prime power (or when called per prime-power factor of n).
sub __dlog_coprime_prime_power_mod__($a, $g, $n) {

    my $order = znorder($g, $n) // return undef;

    # Quick necessary condition: a must lie in the subgroup generated by g
    if (powmod($a, $order, $n) != 1) {
        return undef;
    }

    # Trivial case
    if ($order == 1) {
        return ($a == 1 ? 0 : undef);
    }

    # Factor the order into prime powers and solve for each
    my @factors  = factor_exp($order);
    my @residues = ();

    foreach my $pp (@factors) {
        my ($p, $e)  = @$pp;
        my ($x, $ok) = __prime_power_log__($a, $g, $n, $p, $e, $order);
        $ok || return undef;
        push @residues, [$x, powint($p, $e)];
    }

    # Combine via CRT
    my $x = chinese(@residues);

    # Verify
    (defined($x) && powmod($g, $x, $n) == $a) ? $x : undef;
}

sub discrete_log($a, $g, $n, $order = undef) {

    # Normalise inputs
    $a %= $n;
    $g %= $n;

    # Handle non-coprime case: gcd(g, n) > 1
    if (gcd($g, $n) != 1) {

        my $g_pow = 1;    # g^k mod n (original n), for direct equality check
        my $n_red = $n;   # modulus being reduced
        my $a_red = $a;   # target being reduced
        my $d_acc = 1;    # accumulated product: (g/D_1)*(g/D_2)*...*(g/D_k) mod n_red
        my $k     = 0;

        while (gcd($g, $n_red) != 1) {

            # Check if g^k already equals a (mod n)
            return $k if $g_pow == $a;

            my $D = gcd($g, $n_red);
            return undef if $a_red % $D != 0;

            $n_red = divint($n_red, $D);
            $a_red = divint($a_red, $D);
            $d_acc = mulmod($d_acc, divint($g, $D), $n_red);
            $k++;
            $g_pow = mulmod($g_pow, $g, $n);
        }

        # Final direct check after stripping
        return $k if $g_pow == $a;

        # Phase 2: gcd(g, n_red) = 1 now; solve g^y = a_red * inv(d_acc) (mod n_red)
        my $inv_d = invmod($d_acc, $n_red) // return undef;
        my $a_new = mulmod($a_red, $inv_d, $n_red);
        my $y     = discrete_log($a_new, $g, $n_red);
        return defined($y) ? $k + $y : undef;
    }

    # Coprime case: gcd(g, n) = 1

    # Factor n into prime powers
    my @n_factors = factor_exp($n);

    # For a single prime-power modulus, use Pohlig-Hellman directly
    if (@n_factors == 1) {
        my $ord = $order // znorder($g, $n) // return undef;

        if (powmod($a, $ord, $n) != 1) {
            return undef;
        }

        if ($ord == 1) {
            return ($a == 1 ? 0 : undef);
        }

        my @factors  = factor_exp($ord);
        my @residues = ();

        foreach my $pp (@factors) {
            my ($p, $e)  = @$pp;
            my ($x, $ok) = __prime_power_log__($a, $g, $n, $p, $e, $ord);
            $ok || return undef;
            push @residues, [$x, powint($p, $e)];
        }

        my $x = chinese(@residues);
        return (defined($x) && powmod($g, $x, $n) == $a) ? $x : undef;
    }

    # Composite n: solve g^x = a (mod p^e) for each prime-power factor, then CRT
    my @residues = ();

    foreach my $pp (@n_factors) {
        my ($p, $e) = @$pp;
        my $pe      = powint($p, $e);
        my $g_i     = $g % $pe;
        my $a_i     = $a % $pe;

        my $r = __dlog_coprime_prime_power_mod__($a_i, $g_i, $pe);
        return undef unless defined $r;

        my $ord_i = znorder($g_i, $pe) // return undef;
        push @residues, [$r, $ord_i];
    }

    my $x = chinese(@residues) // return undef;

    # Verify the result
    (powmod($g, $x, $n) == $a) ? $x : undef;
}

use Test::More tests => 14;

is(discrete_log(5678, 5, 10007), 8620);

#is(discrete_log(Math::GMPz->new("232752345212475230211680"), Math::GMPz->new("23847293847923847239847098123812075234"), Math::GMPz->new("804842536444911030681947")), 13);

foreach my $test (
                  [[5675,              5,      10000019],          2003974],            # 5675 = 5^2003974 mod 10000019
                  [[18478760,          5,      314138927],         34034873],
                  [[553521,            459996, 557057],            15471],
                  [[7443282,           4,      13524947],          6762454],
                  [[32712908945642193, 5,      71245073933756341], 5945146967010377],
  ) {
    my ($t, $v) = @$test;
    say "Testing: discrete_log(", join(', ', @$t), ") = ", $v;
    is(discrete_log($t->[0], $t->[1], $t->[2]), $v);
}

is_deeply(
          [map { discrete_log(powint(2, $_) - 5, 3, powint(2, $_ + 1)) } 0 .. 35],
          [undef,  0,       undef,    1,        7,        3,         27,       43,        75,        139,        11,         779,
           267,    1291,    3339,     7435,     32011,    48395,     81163,    146699,    277771,    15627,      1588491,    2637067,
           539915, 4734219, 13122827, 63454475, 29900043, 231226635, 97008907, 902315275, 365444363, 1439186187, 3586669835, 7881637131
          ]
         );

is_deeply([map { discrete_log(-1, 3, powint(3, $_) - 2) // 0 } 2 .. 30],
          [3, 10, 39, 60, 121, 0, 117, 4920, 0, 0, 0, 28322, 0, 1434890, 0, 0, 0, 116226146, 0, 0, 15690529803, 0, 108443565, 66891206007, 0, 0, 0, 0, 0]);

# Non-coprime tests
is(discrete_log(36, 44, 50), 2);    # 44^2 = 1936 = 36 (mod 50), gcd(44,50)=2
is(discrete_log(0,  2,  4),  2);    # 2^2 = 4 = 0 (mod 4)
is(discrete_log(4,  6,  8),  2);    # 6^2 = 36 = 4 (mod 8)

# Composite modulus, coprime base
is(discrete_log(130, 85, 177), 15);    # 177 = 3*59, gcd(85,177)=1
is(discrete_log(100, 52, 209), 10);    # 209 = 11*19, 52^10 = 100 (mod 209)

# Verify no-solution cases still return undef
is(discrete_log(3, 4, 6), undef);    # no solution exists
