#!/usr/bin/perl

use 5.036;
use ntheory qw(:all);

# Pohlig‑Hellman with Pollard’s rho for each prime‑power factor.

# Pollard's rho algorithm for logarithms
# https://en.wikipedia.org/wiki/Pollard%27s_rho_algorithm_for_logarithms

# Pollard's rho for groups of prime order p
sub __prime_order_log__($g, $h, $p, $n, $max_tries = 100) {

    # Trivial cases
    return 0 if ($h == 1);
    return 1 if ($g == $h);

    foreach my $attempt (1 .. $max_tries) {

        # Random starting point (a,b) with X = g^a * h^b
        my $a1 = urandomm($p);
        my $b1 = urandomm($p);
        my $x1 = mulmod(powmod($g, $a1, $n), powmod($h, $b1, $n), $n);

        my $a2 = $a1;
        my $b2 = $b1;
        my $x2 = $x1;

        # Floyd's cycle detection
        my $iter = sub($a, $b, $x) {
            my $r = ($x % 3);
            if ($r == 0) {
                $a = addmod($a, 1, $p);
                $x = mulmod($x, $g, $n);
            }
            elsif ($r == 1) {
                $b = addmod($b, 1, $p);
                $x = mulmod($x, $h, $n);
            }
            else {
                $a = mulmod(2,  $a, $p);
                $b = mulmod(2,  $b, $p);
                $x = mulmod($x, $x, $n);
            }
            return ($a, $b, $x);
        };

        while (1) {

            # Tortoise step
            ($a1, $b1, $x1) = $iter->($a1, $b1, $x1);

            # Hare step (two iterations)
            ($a2, $b2, $x2) = $iter->($a2, $b2, $x2);
            ($a2, $b2, $x2) = $iter->($a2, $b2, $x2);

            if ($x1 == $x2) {

                # Collision: g^{a1} h^{b1} = g^{a2} h^{b2}
                my $da = submod($a1, $a2, $p);
                my $db = submod($b2, $b1, $p);

                if ($db == 0) {
                    last;    # degenerate case, restart
                }

                my $x = mulmod($da, invmod($db, $p), $p);

                if (powmod($g, $x, $n) == $h) {
                    return $x;
                }
                last;    # verification failed, restart
            }
        }
    }

    return undef;    # failed after max_tries
}

# Solve g^x = a (mod n) where g has order exactly p^e * r,
# and we want x modulo p^e.
sub __prime_power_log__($a, $g, $n, $p, $e, $full_order) {

    my $L = $full_order;
    my $r = divint($L, powint($p, $e));    # co‑factor

    # Move into the subgroup of order p^e
    my $g0 = powmod($g, $r, $n);
    my $a0 = powmod($a, $r, $n);

    my $x     = 0;
    my $cur_g = $g0;                       # current generator, order p^{e-i}
    my $cur_a = $a0;                       # current element
    my $f     = 1;                         # current digit multiplier

    foreach my $i (0 .. $e - 1) {

        # Create an element of order p by raising to p^{e-1-i}
        my $exp   = powint($p, $e - $i - 1);
        my $sub_g = powmod($cur_g, $exp, $n);    # generator of order p
        my $sub_a = powmod($cur_a, $exp, $n);    # corresponding element

        # Solve the discrete log in the prime‑order subgroup
        my $d = __prime_order_log__($sub_g, $sub_a, $p, $n) // return (undef, 0);

        $x += ($d * $f);
        $f *= $p;

        # Remove the already found part
        $cur_a = mulmod($cur_a, powmod($cur_g, -$d, $n), $n);
        $cur_g = powmod($cur_g, $p, $n);                        # next generator, order p^{e-1-i}
    }

    return ($x, 1);
}

sub discrete_log($a, $g, $n, $order = undef) {

    # Normalise inputs
    $a %= $n;
    $g %= $n;

    # g must be invertible modulo n
    if (gcd($g, $n) != 1) {
        return undef;
    }

    # Determine the order of g if not provided
    $order //= znorder($g, $n) // return undef;

    # Quick necessary condition: a must lie in the subgroup generated by g
    if (powmod($a, $order, $n) != 1) {
        return undef;
    }

    # Trivial cases
    if ($order == 1) {
        return ($a == 1 ? 0 : undef);
    }

    # Factor the order into prime powers
    my @factors = factor_exp($order);

    # Solve for x modulo each prime power
    my @residues;

    foreach my $pp (@factors) {
        my ($p, $e)  = @$pp;
        my ($x, $ok) = __prime_power_log__($a, $g, $n, $p, $e, $order);
        $ok || return undef;
        push @residues, [$x, powint($p, $e)];
    }

    # Combine via CRT
    my $x = chinese(@residues);

    # Verify the result (should always hold if the algorithm succeeded)
    (powmod($g, $x, $n) == $a) ? $x : undef;
}

use Test::More tests => 8;

is(discrete_log(5678, 5, 10007), 8620);

#is(discrete_log(Math::GMPz->new("232752345212475230211680"), Math::GMPz->new("23847293847923847239847098123812075234"), Math::GMPz->new("804842536444911030681947")), 13);

foreach my $test (
                  [[5675,              5,      10000019],          2003974],            # 5675 = 5^2003974 mod 10000019
                  [[18478760,          5,      314138927],         34034873],
                  [[553521,            459996, 557057],            15471],
                  [[7443282,           4,      13524947],          6762454],
                  [[32712908945642193, 5,      71245073933756341], 5945146967010377],
  ) {
    my ($t, $v) = @$test;
    say "Testing: discrete_log(", join(', ', @$t), ") = ", $v;
    is(discrete_log($t->[0], $t->[1], $t->[2]), $v);
}

is_deeply(
          [map { discrete_log(powint(2, $_) - 5, 3, powint(2, $_ + 1)) } 0 .. 35],
          [undef,  0,       undef,    1,        7,        3,         27,       43,        75,        139,        11,         779,
           267,    1291,    3339,     7435,     32011,    48395,     81163,    146699,    277771,    15627,      1588491,    2637067,
           539915, 4734219, 13122827, 63454475, 29900043, 231226635, 97008907, 902315275, 365444363, 1439186187, 3586669835, 7881637131
          ]
         );

is_deeply([map { discrete_log(-1, 3, powint(3, $_) - 2) // 0 } 2 .. 30],
          [3, 10, 39, 60, 121, 0, 117, 4920, 0, 0, 0, 28322, 0, 1434890, 0, 0, 0, 116226146, 0, 0, 15690529803, 0, 108443565, 66891206007, 0, 0, 0, 0, 0]);
