#!/usr/bin/perl

use strict;
use GD::Simple;

my $img = 'GD::Simple'->new(2503, 2500);

$img->moveTo(540, 1980);

my $nr = 360;

foreach $_ (0 .. 410) {
    $img->fgcolor('purple');
    $img->turn(-90);
    $img->line(--$nr / 10);
    $img->turn(90);
    $img->line($nr);
    $img->turn(90);
    $img->line($nr / 10);
    $img->turn(90);
    $img->move($nr / 2);
    $img->turn(90);
    $img->move($nr / 10);
    $img->turn(-180);
    $img->line($nr);
    $img->turn(-90);
    $img->fgcolor('green');
    $img->move($nr / 1.5);
    $img->turn(-90);
    $img->line($nr);
    $img->turn(90);
    $img->line($nr / 2 - $nr / 10);
    $img->turn(45);
    $img->line($nr / 10);
    $img->turn(45);
    $img->line($nr / 2 - $nr / 10);
    $img->turn(45);
    $img->line($nr / 10);
    $img->turn(45);
    $img->line($nr / 2 - $nr / 10);
    $img->turn(-135);
    $img->line($nr / 2 + $nr / 4 - $nr / 10);
    $img->turn(-135);
    $img->line($nr / 10);
    $img->turn(180);
    $img->move($nr / 10);
    $nr -= $_;
    $img->fgcolor('black');
    $img->turn(-90);
    $img->move($nr / 4);
    $img->turn(-90);
    $img->line($nr);
    $img->move($nr / 10);
    $img->turn(180);
    $img->move($nr / 10 + 12 + 6);
    $img->turn(-90);
    $img->move($nr / 5);
    $img->line(12);
    $img->turn(180);
    $img->line(-12);
    $img->line(12);
    $img->turn(45);
    $img->line(-12);
    $img->turn(180);
    $img->line(12);
    $img->line(-12);
    $img->turn(45);
    $img->line(12);
    $img->turn(180);
    $img->line(-12);
    $img->line(12);
    $img->turn(45);
    $img->line(-12);
    $img->turn(180);
    $img->line(12);
    $img->line(-12);
    $img->turn(45);
    $img->line(12);
    $img->turn(180);
    $img->line(-12);
    $img->line(12);
    $img->turn(45);
    $img->line(-12);
    $img->turn(180);
    $img->line(12);
    $img->line(-12);
    $img->turn(45);
    $img->line(12);
    $img->turn(180);
    $img->line(-12);
    $img->line(12);
    $img->turn(45);
    $img->line(-12);
    $img->turn(180);
    $img->line(12);
    $img->line(-12);
    $nr += $_;
    $img->fgcolor('red');
    $img->turn(-45);
    $img->move($nr + 72);
    $img->turn(-90);
    $img->move($nr / 7);
    $img->turn(-65);
    $img->line($nr + $nr / 10);
    $img->turn(-115);
    $img->line($nr / 2);
    $img->turn(-90);
    $img->line($nr / 10);
    $img->turn(180);
    $img->move($nr / 10);
    $img->turn(155);
    $img->move($nr + $nr / 10);
    $img->turn(-155);
    $img->line($nr / 10);
    $img->turn(180);
    $img->move($nr / 10);
    $img->turn(90);
    $img->line($nr / 2 - $nr / 7 / 2);
    $img->turn(115);
    $img->move(($nr + $nr / 10) / 2);
    $img->turn(-115);
    $img->line($nr / 4);
    $img->turn(-90);
    $img->line($nr / 10);
    $img->turn(180);
    $img->move($nr / 10);
    $img->turn(90);
    $img->line($nr / 2);
    $img->turn(-90);
    $img->line($nr / 10);
    $img->fgcolor('orange');
    $img->turn(180);
    $img->move($nr / 2 + $nr / 10);
    $img->turn(-90);
    $img->move($nr / 5);
    $img->turn(-90);
    $img->line($nr);
    $img->turn(90);
    $img->line($nr / 2);
    $img->turn(90);
    $img->move($nr / 2);
    $img->turn(90);
    $img->line($nr / 2);
    $img->turn(-90);
    $img->move($nr / 2);
    $img->line($nr / 2);
    $img->fgcolor('blue');
    $img->turn(0);
    $img->move($nr / 4);
    $img->turn(-90);
    $img->line($nr);
    $img->turn(155);
    $img->line($nr + $nr / 10);
    $img->turn(-155);
    $img->line($nr);
}

my $image_name = 'turtle.png';
die $! unless open my $fh, '>', $image_name;

print $fh $img->png;
close $fh;

system 'geeqie', $image_name;
